# Generated by Django 2.1.7 on 2019-04-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('mail', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employee_details',
            },
        ),
    ]
