# Generated by Django 2.1.7 on 2019-04-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_de',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('website', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employee_de',
            },
        ),
        migrations.DeleteModel(
            name='employee_details',
        ),
    ]
