# Generated by Django 2.1.7 on 2019-04-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_auto_20190419_1101'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee_de',
            table=None,
        ),
    ]
