# Generated by Django 2.1.7 on 2019-04-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_auto_20190419_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_de',
            name='phonenumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
