# Generated by Django 2.1.7 on 2019-04-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_auto_20190419_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_de',
            name='phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='employee_de',
            table='employee_de',
        ),
    ]
