# Generated by Django 2.1.7 on 2019-04-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_auto_20190419_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_de',
            name='phonenumber',
        ),
    ]
