# Generated by Django 2.1.7 on 2019-04-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_auto_20190420_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women_shops_clothes',
            old_name='price',
            new_name='Price',
        ),
    ]
