# Generated by Django 2.1.7 on 2019-04-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_auto_20190420_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='women_shops_clothes',
            new_name='women_shops',
        ),
        migrations.AlterModelTable(
            name='women_shops',
            table='women_shops',
        ),
    ]
