# Generated by Django 2.1.7 on 2019-04-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_auto_20190420_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
            ],
            options={
                'db_table': 'clothes',
            },
        ),
        migrations.CreateModel(
            name='footware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
            ],
            options={
                'db_table': 'footware',
            },
        ),
        migrations.RenameModel(
            old_name='women_shops',
            new_name='accessories',
        ),
        migrations.AlterModelTable(
            name='accessories',
            table='Accessories',
        ),
    ]
