# Generated by Django 2.1.7 on 2019-04-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0010_auto_20190420_1601'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clothes',
            new_name='clothe',
        ),
    ]
