# Generated by Django 2.1.7 on 2019-04-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_auto_20190420_1633'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clothe',
            table='clothe',
        ),
    ]
