# Generated by Django 2.1.7 on 2019-04-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0012_auto_20190420_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accessories',
        ),
        migrations.DeleteModel(
            name='footware',
        ),
    ]
