# Generated by Django 2.1.7 on 2019-04-27 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0014_accessories_footware'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=8)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='accessories',
        ),
        migrations.DeleteModel(
            name='clothe',
        ),
        migrations.DeleteModel(
            name='footware',
        ),
    ]
